#!/bin/bash

getAudioVolume(){
    amixer -D pulse sget Master | grep 'Front Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'
}

getAudioIcon(){
    if amixer -D pulse sget Master | grep 'Front Left:' | grep -q '\[off\]'; then
        echo "󰖁"
    else
        percentage=$(getAudioVolume)
        if [[ $percentage -eq 0 ]]; then
            echo "󰕿"
        elif [[ $percentage -gt 0 ]] && [[ $percentage -le 50 ]]; then
            echo "󰖀"
        elif [[ $percentage -gt 50 ]] && [[ $percentage -lt 100 ]]; then
            echo "󰕾"
        else
            echo ""
        fi
    fi
}

update(){
    icon=$(getAudioIcon)
    volume=$(getAudioVolume)
    jq -n -r -c --arg icon "$icon" --argjson volume "$volume" '{icon: $icon, volume: $volume}'
}

# Initial update
update

# Listen for changes in audio
pactl subscribe | grep --line-buffered "Event 'change' on sink #" | while read -r _ ; do
    update
done
