#!/bin/bash

getAudioVolume(){
    amixer -D pulse sget Master | grep 'Front Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%'
}

getAudioIcon(){
    if [[ $(pactl list sinks | grep "Mute: yes") ]]; then
    # use nerd font icon
        echo "󰖁"
    else
        # get percentage
        percentage=$(getAudioVolume)
        # get icon
        if [[ $percentage -eq 0 ]]; then
            echo "󰕿"
        elif [[ $percentage -gt 0 ]] && [[ $percentage -le 50 ]]; then
            echo "󰖀"
        elif [[ $percentage -gt 50 ]] && [[ $percentage -lt 100 ]]; then
            echo "󰕾"
        else
            echo ""
        fi
    fi
}

if [[ "$1" == "--icon" ]]; then
    getAudioIcon
elif [[ "$1" == "--volume" ]]; then
    getAudioVolume
fi