#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
BAR_HOME="$HOME/.config/hypr/bar/saimoomedits/eww/bar"
EWW="eww -c $BAR_HOME"

$BAR_HOME/update_bar_windows.sh

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many $(hyprctl monitors -j | jq -r '.[] | "bar" +(.id|tostring)' | tr '\n' ' ' | xargs)
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww && bspc config -m LVDS-1 top_padding 49
else
	${EWW} close-all && killall eww
	rm "$FILE"
fi
